DROP TABLE IF EXISTS SOMETHING;
CREATE TABLE SOMETHING (
  ID int unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(16) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  USERNAME varchar(16) NOT NULL,
  PASSWORD varchar(16) NOT NULL,
  PRIMARY KEY (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;